accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from accountapp.views import AccountCreateView, AccountDeleteView, AccountDetailView, AccountUpdateView, hello_world2

app_name = 'accountapp'

urlpatterns = [
    path('helloworld2/',hello_world2, name='helloworld2'),
    
    path('login/',LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    
    path('create/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleListView, ArticleUpdateView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(),name='list'),
    path('ceate/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(),name='delete'),
]

lolstatyong/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('rankstatapp.urls')),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('projects/',include('projectapp.urls')),
    path('subscribe/',include('subscribeapp.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView


app_name = 'projectapp'

urlpatterns = [
    path('list/',ProjectListView.as_view(), name='list'),
    path('create/',ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(), name='detail'),
]

rankstatapp/urls.py
from django.urls import path

from rankstatapp.views import Current_game_Participants, hello_world, ranksearch

app_name = "rankstatapp"

urlpatterns = [
    path('hello_world/',hello_world, name='helloworld'),
    path('home/',hello_world, name='home'),
    path('summoners/',ranksearch, name='summoners'),
    path('current_game/',Current_game_Participants, name='current_game'),

]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionListView, SubscriptionView


app_name = "subscribeapp"

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe' ),
    path('list/', SubscriptionListView.as_view(), name='list' )
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">


{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>
    
    
    {% block content %}
        
    {% endblock content %}
        

    {% block summoner_stat %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="lolstatyong_footer">

    <div class="lolstatyong_footer_button">
        <span>Announcement</span> |
        <span>Contact</span> |
        <span>About Us</span>
        
    </div>
    <div class="lolstatyong_logo">
        <h6>LOLStatYong</h6>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>lolstatyong</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <!-- DEFAULT CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!-- fonts -->
    <style>
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div class="lolstatyong_header">
    <a href="{%url 'rankstatapp:summoners'%}">LOLStatYong</a>
</div>

<div class="lolstatyong_header_navbar">
    <a href="{% url 'articleapp:list' %}" class="lolstatyong_header_nav">
        <span>자유주제</span>
    </a> |
    <a href="{% url 'articleapp:list' %}" class="lolstatyong_header_nav">
        <span>챔피언 상대법</span>
    </a> |
    <a href="{% url 'projectapp:list' %}" class="lolstatyong_header_nav">
        <span>카테고리</span>
    </a> |
    <a href="{% url 'subscribeapp:list' %}" class="lolstatyong_header_nav">
        <span>구독게시글</span>
    </a> |
    {% if not user.is_authenticated %}    
    <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="lolstatyong_header_nav">
        <span>로그인</span>
    </a> |
    <a href="{% url 'accountapp:create' %}" class="lolstatyong_header_nav">
        <span>회원가입</span>
    </a>
    {% else %}
    <a href="{% url 'accountapp:detail' pk=user.pk%}" class="lolstatyong_header_nav">
        <span>마이 페이지</span> |
    </a>
    <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="lolstatyong_header_nav">
        <span>로그아웃</span>
    </a>
    {% endif %}
</div>

<div style="text-align: center; margin-bottom:1rem;">
    <form action="{% url 'rankstatapp:summoners'%}?name={{name}}&region={{region}}" method="GET">
    <div>
        <select name='region' onchange="region=this.value;">
            <option value='kr'>KR</option>
            <option value='na1'>NA</option>
            <option value='jp'>JP</option>
        </select>
    아이디: <input name="name">
    <input type="submit" value="Submit">
    </div>
    </form>
</div>